/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.responses;

import java.util.List;

public class Backplane extends ApiResponse {

    private List<Server> backplane_servers;
    
    public class Server {
        
        private String bus;
        private String username;
        private String server;
        private String version;
        private String password;
        
        public String getBus() {
            return bus;
        }
        
        public void setBus(String bus) {
            this.bus = bus;
        }
        
        public String getUsername() {
            return username;
        }
        
        public void setUsername(String username) {
            this.username = username;
        }
        
        public String getServer() {
            return server;
        }
        
        public void setServer(String server) {
            this.server = server;
        }
        
        public String getVersion() {
            return version;
        }
        
        public void setVersion(String version) {
            this.version = version;
        }
        
        public String getPassword() {
            return password;
        }
        
        public void setPassword(String password) {
            this.password = password;
        }
        
    }

    public List<Server> getBackplane_servers() {
        return backplane_servers;
    }

    public void setBackplane_servers(List<Server> backplane_servers) {
        this.backplane_servers = backplane_servers;
    }
    
}