/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.responses;

import java.util.List;

public class Broadcast {
    
    private String status;
    private Response response;
    
    public class Response {
        
        private String provider;
        private String mode;
        private boolean success;
        private List<Result> results;
        
        public class Result {
            
            private boolean success;
            private Share share;
            
            public class Share {
                
                private String message;
                private String title;
                private String url;
                private String image;
                private String media;
                private ActionLink actionLink;
                
                public class ActionLink {
                    
                    private String name;
                    private String link;
                    public String getName() {
                        return name;
                    }
                    public void setName(String name) {
                        this.name = name;
                    }
                    public String getLink() {
                        return link;
                    }
                    public void setLink(String link) {
                        this.link = link;
                    }
                    
                }

                public String getMessage() {
                    return message;
                }

                public void setMessage(String message) {
                    this.message = message;
                }

                public String getTitle() {
                    return title;
                }

                public void setTitle(String title) {
                    this.title = title;
                }

                public String getUrl() {
                    return url;
                }

                public void setUrl(String url) {
                    this.url = url;
                }

                public String getImage() {
                    return image;
                }

                public void setImage(String image) {
                    this.image = image;
                }

                public String getMedia() {
                    return media;
                }

                public void setMedia(String media) {
                    this.media = media;
                }

                public ActionLink getActionLink() {
                    return actionLink;
                }

                public void setActionLink(ActionLink actionLink) {
                    this.actionLink = actionLink;
                }
                
            }

            public boolean isSuccess() {
                return success;
            }

            public void setSuccess(boolean success) {
                this.success = success;
            }

            public Share getShare() {
                return share;
            }

            public void setShare(Share share) {
                this.share = share;
            }
            
        }

        public String getProvider() {
            return provider;
        }

        public void setProvider(String provider) {
            this.provider = provider;
        }

        public String getMode() {
            return mode;
        }

        public void setMode(String mode) {
            this.mode = mode;
        }

        public boolean isSuccess() {
            return success;
        }

        public void setSuccess(boolean success) {
            this.success = success;
        }

        public List<Result> getResults() {
            return results;
        }

        public void setResults(List<Result> results) {
            this.results = results;
        }

    }
    
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Response getResponse() {
        return response;
    }

    public void setResponse(Response response) {
        this.response = response;
    }
    
}