/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.engage;

public class AuthInfos extends ApiResponse {

    private Profile profile;
    
    public class Profile {
        
        private String displayName;
        private String preferredUsername;
        private String url;
        private String providerName;
        private String identifier;
        
        public String getDisplayName() {
            return displayName;
        }
        
        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }
        
        public String getPreferredUsername() {
            return preferredUsername;
        }
        
        public void setPreferredUsername(String preferredUsername) {
            this.preferredUsername = preferredUsername;
        }
        
        public String getUrl() {
            return url;
        }
        
        public void setUrl(String url) {
            this.url = url;
        }
        
        public String getProviderName() {
            return providerName;
        }
        
        public void setProviderName(String providerName) {
            this.providerName = providerName;
        }
        
        public String getIdentifier() {
            return identifier;
        }
        
        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }

    }
    
    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    
}