/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.engage;

import java.util.List;

public class Providers extends ApiResponse {
    
    private List<String> signin;
    private List<String> social;
    
    public List<String> getSignin() {
        return signin;
    }
    
    public void setSignin(List<String> signin) {
        this.signin = signin;
    }
    
    public List<String> getSocial() {
        return social;
    }
    
    public void setSocial(List<String> social) {
        this.social = social;
    }

}