/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.engage;

import java.util.List;

public class Providers extends ApiResponse {
    
    private List<String> signin;
    private List<String> social;
    
    public List<String> getSignin() {
        return signin;
    }
    
    public void setSignin(List<String> signin) {
        this.signin = signin;
    }
    
    public List<String> getSocial() {
        return social;
    }
    
    public void setSocial(List<String> social) {
        this.social = social;
    }

}