/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.engage;

import java.util.List;

public class UserInfo extends ApiResponse {
    
    private Profile profile;
    private AccessCredentials accessCredentials;
    private Merged_poco merged_poco;
    
    public class Profile {
        
        private String email;
        private String identifier;
        private String providerName;
        private String url;
        private String preferredUsername;
        private String displayName;
        private String googleUserId;
        private String verifiedEmail;
        private Name name;
        
        public class Name {
            
            private String givenName;
            private String familyName;
            private String formatted;
            
            public String getGivenName() {
                return givenName;
            }
            
            public void setGivenName(String givenName) {
                this.givenName = givenName;
            }
            
            public String getFamilyName() {
                return familyName;
            }
            
            public void setFamilyName(String familyName) {
                this.familyName = familyName;
            }
            
            public String getFormatted() {
                return formatted;
            }
            
            public void setFormatted(String formatted) {
                this.formatted = formatted;
            }
             
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public String getIdentifier() {
            return identifier;
        }

        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }

        public String getProviderName() {
            return providerName;
        }

        public void setProviderName(String providerName) {
            this.providerName = providerName;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getPreferredUsername() {
            return preferredUsername;
        }

        public void setPreferredUsername(String preferredUsername) {
            this.preferredUsername = preferredUsername;
        }

        public String getDisplayName() {
            return displayName;
        }

        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }

        public String getGoogleUserId() {
            return googleUserId;
        }

        public void setGoogleUserId(String googleUserId) {
            this.googleUserId = googleUserId;
        }

        public String getVerifiedEmail() {
            return verifiedEmail;
        }

        public void setVerifiedEmail(String verifiedEmail) {
            this.verifiedEmail = verifiedEmail;
        }

        public Name getName() {
            return name;
        }

        public void setName(Name name) {
            this.name = name;
        }
        
    }
    
    public class AccessCredentials {
        
        private String scopes;
        private String oauthToken;
        private String type;
        private String oauthTokenSecret;
        
        public String getScopes() {
            return scopes;
        }
        
        public void setScopes(String scopes) {
            this.scopes = scopes;
        }
        
        public String getOauthToken() {
            return oauthToken;
        }
        
        public void setOauthToken(String oauthToken) {
            this.oauthToken = oauthToken;
        }
        
        public String getType() {
            return type;
        }
        
        public void setType(String type) {
            this.type = type;
        }
        
        public String getOauthTokenSecret() {
            return oauthTokenSecret;
        }
        
        public void setOauthTokenSecret(String oauthTokenSecret) {
            this.oauthTokenSecret = oauthTokenSecret;
        }

    }
    
    public class Merged_poco {
        
        private List<TypeValue> emails;
        private List<TypeValue> urls;
        private List<String> languagesSpoken;
        private String preferredUsername;
        private Name name;
        
        public class Name {
            
            private String givenName;
            private String familyName;
            private String formatted;
            
            public String getGivenName() {
                return givenName;
            }
            
            public void setGivenName(String givenName) {
                this.givenName = givenName;
            }
            
            public String getFamilyName() {
                return familyName;
            }
            
            public void setFamilyName(String familyName) {
                this.familyName = familyName;
            }
            
            public String getFormatted() {
                return formatted;
            }
            
            public void setFormatted(String formatted) {
                this.formatted = formatted;
            }
             
        }
        
        public class TypeValue {
            
            private String type;
            private String value;
            
            public String getType() {
                return type;
            }
            
            public void setType(String type) {
                this.type = type;
            }
            
            public String getValue() {
                return value;
            }
            
            public void setValue(String value) {
                this.value = value;
            }

        }

        public List<TypeValue> getEmails() {
            return emails;
        }

        public void setEmails(List<TypeValue> emails) {
            this.emails = emails;
        }
        
        public List<TypeValue> getUrls() {
            return urls;
        }
        
        public void setUrls(List<TypeValue> urls) {
            this.urls = urls;
        }
        
        public List<String> getLanguagesSpoken() {
            return languagesSpoken;
        }
        
        public void setLanguagesSpoken(List<String> languagesSpoken) {
            this.languagesSpoken = languagesSpoken;
        }
        
        public String getPreferredUsername() {
            return preferredUsername;
        }
        
        public void setPreferredUsername(String preferredUsername) {
            this.preferredUsername = preferredUsername;
        }
        
        public Name getName() {
            return name;
        }
        
        public void setName(Name name) {
            this.name = name;
        }
    
    }

    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public AccessCredentials getAccessCredentials() {
        return accessCredentials;
    }

    public void setAccessCredentials(AccessCredentials accessCredentials) {
        this.accessCredentials = accessCredentials;
    }

    public Merged_poco getMerged_poco() {
        return merged_poco;
    }

    public void setMerged_poco(Merged_poco merged_poco) {
        this.merged_poco = merged_poco;
    }
    
}