/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.engage;

import java.util.List;

public class WidgetProviders extends Providers {
    
    private Share shareWidget;
    
    public class Share {
        
        private List<String> share;
        private List<String> email;
        
        public List<String> getShare() {
            return share;
        }

        public void setShare(List<String> share) {
            this.share = share;
        }

        public List<String> getEmail() {
            return email;
        }
        
        public void setEmail(List<String> email) {
            this.email = email;
        }
        
    }

    public Share getShareWidget() {
        return shareWidget;
    }

    public void setShareWidget(Share shareWidget) {
        this.shareWidget = shareWidget;
    }
    
}