/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.partner;

public class AppInfo {
    
    private Response partnerresponse;
    
    public class Response {
        
        private String stat;
        private String apikey;
        private String adminurl;
        private String inviteurl;
        private String realm;
        private String appid;
        
        public String getStat() {
            return stat;
        }
        
        public void setStat(String stat) {
            this.stat = stat;
        }
        
        public String getApikey() {
            return apikey;
        }
        
        public void setApikey(String apikey) {
            this.apikey = apikey;
        }
        
        public String getAdminurl() {
            return adminurl;
        }
        
        public void setAdminurl(String adminurl) {
            this.adminurl = adminurl;
        }
        
        public String getInviteurl() {
            return inviteurl;
        }
        
        public void setInviteurl(String inviteurl) {
            this.inviteurl = inviteurl;
        }
        
        public String getRealm() {
            return realm;
        }
        
        public void setRealm(String realm) {
            this.realm = realm;
        }
        
        public String getAppid() {
            return appid;
        }

        public void setAppid(String appid) {
            this.appid = appid;
        }

    }

    public Response getPartnerresponse() {
        return partnerresponse;
    }

    public void setPartnerresponse(Response partnerresponse) {
        this.partnerresponse = partnerresponse;
    }
    
}