/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain;

import java.util.Map;

import org.mule.api.ConnectionException;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.licensing.RequiresEnterpriseLicense;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.modules.janrain.capture.BulkResponse;
import org.mule.modules.janrain.capture.ClientInfo;
import org.mule.modules.janrain.capture.ClientListInfo;
import org.mule.modules.janrain.client.JanrainCaptureClient;
import org.mule.modules.janrain.client.JanrainCaptureClientImpl;
import org.mule.modules.janrain.client.JanrainEngageClient;
import org.mule.modules.janrain.client.JanrainEngageClientImpl;
import org.mule.modules.janrain.client.JanrainPartnerClient;
import org.mule.modules.janrain.client.JanrainPartnerClientImpl;
import org.mule.modules.janrain.engage.AuthInfos;
import org.mule.modules.janrain.engage.AvailableProviders;
import org.mule.modules.janrain.engage.Backplane;
import org.mule.modules.janrain.engage.Broadcast;
import org.mule.modules.janrain.engage.Contacts;
import org.mule.modules.janrain.engage.Direct;
import org.mule.modules.janrain.engage.DomainPatterns;
import org.mule.modules.janrain.engage.Identifiers;
import org.mule.modules.janrain.engage.Plugin;
import org.mule.modules.janrain.engage.ShareProviders;
import org.mule.modules.janrain.engage.UserInfo;
import org.mule.modules.janrain.engage.WidgetProviders;
import org.mule.modules.janrain.partner.Admins;
import org.mule.modules.janrain.partner.AppInfo;
import org.mule.modules.janrain.partner.Apps;
import org.mule.modules.janrain.partner.Invites;
import org.mule.modules.janrain.partner.Permissions;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.api.json.JSONConfiguration;
import com.sun.jersey.core.impl.provider.entity.FormMultivaluedMapProvider;
import com.sun.jersey.core.impl.provider.entity.FormProvider;
import com.sun.jersey.core.impl.provider.entity.InputStreamProvider;
import com.sun.jersey.core.impl.provider.entity.MimeMultipartProvider;
import com.sun.jersey.multipart.impl.MultiPartWriter;

/**
 * Janrain Cloud Connector for API V2.
 *
 * @author MuleSoft, Inc.
 */

@Connector(name="janrain", schemaVersion="2.0", friendlyName="Janrain", minMuleVersion="3.4")
@RequiresEnterpriseLicense
public class JanrainConnector {
        
    /**
     * The App Name
     */
    private String appName;
    
    /**
     * The App ID
     */
    private String appId;
    
    /**
     * The capture host
     */
    private String captureHost;
    
    /**
     * The Api Key
     */
    private String apiKey;
            
    /**
     * Janrain Engage Client
     */
    private JanrainEngageClient janrainEngageClient;
    
    /**
     * Janrain Partner Client
     */
    private JanrainPartnerClient janrainPartnerClient;
    
    /**
     * Janrain Capture Client
     */
    private JanrainCaptureClient janrainCaptureClient;
    
    /**
     * Jersey Client
     */
    private Client jerseyClient;
    
    /**
     * Gson Parser
     */
    private Gson gson;
    
    /**
     * Connect
     *
     * @param apiKey The "API key (secret)" provided in the "Application Info"
     * @param appName The name of your application. In "Application Domain" -> https://[appName].rpxnow.com/
     * @param appId The "App ID" provided in the "Application Info"
     * @param captureHost The host that you will using for your capture API. It might be the same as "Application Domain" or you can personalize this one
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String apiKey, String appName, String appId, String captureHost) throws ConnectionException {
        ClientConfig clientConfig = new DefaultClientConfig();
        clientConfig.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING, Boolean.TRUE);
        clientConfig.getClasses().add(MultiPartWriter.class);
        clientConfig.getClasses().add(MimeMultipartProvider.class);
        clientConfig.getClasses().add(InputStreamProvider.class);
        clientConfig.getClasses().add(FormProvider.class);
        clientConfig.getClasses().add(FormMultivaluedMapProvider.class);
        
        this.setAppId(appId);
        this.setApiKey(apiKey);
        this.setAppName(appName);
        this.setCaptureHost(captureHost);
        this.gson = new GsonBuilder().create();
        this.setJerseyClient(Client.create(clientConfig));
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        this.jerseyClient = null;
        this.janrainEngageClient = null;
        this.janrainPartnerClient = null;
        this.janrainCaptureClient = null;
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return (this.jerseyClient != null && this.janrainEngageClient != null && this.janrainPartnerClient != null && this.janrainCaptureClient != null);
    }

    /**
     * Connection Id
     */
    @ConnectionIdentifier
    public String connectionId() {
        return apiKey;
    }

    /**
     * Auth Info
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-info}
     *
     * @param token The token parameter received at your token_url.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format. 
     *        Ignored unless the application has a Pro or Enterprise service level.
     * @param tokenURL Validate the specified tokenURL value against the tokenURL that was originally sent. 
     * @return the auth info
     */
    @Processor
    public UserInfo authInfo(String token, @Optional Boolean extended, @Optional String tokenURL) {
        return getJanrainEngageClient().authInfo(token, extended, tokenURL);
    }
    
    /**
     * Add Or Update Access Token
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-or-update-access-token}
     *
     * @param token The access_token to grant to the user. 
     *        These tokens need to be requested from the individual Identity Provider according to their particular API.
     * @param identifier The identifier associated with the provider. This needs to to be formatted as a URL with profile number.
     * @return true if the operation is successful
     */
    @Processor
    public boolean addOrUpdateAccessToken(String token, String identifier) {
        return getJanrainEngageClient().addOrUpdateAccessToken(token, identifier);
    }
    
    /**
     * Analytics Access
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:analytics-access}
     *
     * @param start A date formatted as MM/DD/YYYY.
     * @param end A date formatted as MM/DD/YYYY.
     * @return the analytic data from your application
     */
    @Processor
    public Map<String, String> analyticsAccess(String start, String end) {
        return getJanrainEngageClient().analyticsAccess(start, end);
    }
    
    /**
     * Get App Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-app-settings}
     *
     * @return the app settings
     */
    @Processor
    public Map<String, String> getAppSettings() {
        return getJanrainEngageClient().getAppSettings();
    }
    
    /**
     * Get Available Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-available-providers}
     *
     * @return a list of configured providers for an application
     */
    @Processor
    public AvailableProviders getAvailableProviders() {
        return getJanrainEngageClient().getAvailableProviders();
    }
    
    /**
     * Get Contacts
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-contacts}
     *
     * @param identifier The identifier returned from the auth_info API call. 
     *                   The application must be configured to request this information in the Provider Configuration screen.
     * @param contactType Specify friends to return identifiers for every friend of the user. 
     *                    If you do not specify a value, friends will be returned if available.
     * @param existingUser If true returns a value that identifies if a user has previously authenticated with the Janrain application before.
     * @return a list of all the contacts related to the user
     */
    @Processor
    public Contacts getContacts(String identifier, @Optional String contactType, @Optional Boolean existingUser) {
        return getJanrainEngageClient().getContacts(identifier, contactType, existingUser);
    }
    
    /**
     * Get User Data
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-user-data}
     *
     * @param identifier The identifier returned from the auth_info API call. 
     *                   The application must be configured to request this information in the Provider Configuration screen.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format.
     * @return up-to-date copy of a user’s profile
     */
    @Processor
    public UserInfo getUserData(String identifier, @Optional Boolean extended) {
        return getJanrainEngageClient().getUserData(identifier, extended);
    }
    
    /**
     * Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:providers}
     *
     * @return configured sign-in or social providers configured for a widget
     */
    @Processor
    public WidgetProviders providers() {
        return getJanrainEngageClient().providers();
    }
    
    /**
     * Set App Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-app-settings}
     *
     * @param privacyPolicy Full URL to the location of your privacy policy.
     * @param favicon URL of your favicon.
     * @param domainRedirect The URL for the redirect.
     * @param postToTokenUrl A boolean, true or false.
     * @param oneTimeUseTokens A boolean, true or false.
     * @param googleProfileUrl A boolean, true or false.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setAppSettings(@Optional String privacyPolicy, @Optional String favicon, @Optional String domainRedirect, 
            @Optional Boolean postToTokenUrl, @Optional Boolean oneTimeUseTokens, @Optional Boolean googleProfileUrl) {
        return getJanrainEngageClient().setAppSettings(privacyPolicy, favicon, domainRedirect, postToTokenUrl, oneTimeUseTokens, googleProfileUrl);
    }
    
    /**
     * Set Auth Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-auth-providers}
     *
     * @param providers A comma separated string of provider specifiers.
     * @param deviceType web, iphone, android.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setAuthProviders(String providers, @Optional String deviceType) {
        return getJanrainEngageClient().setAuthProviders(providers, deviceType);
    }
    
    /**
     * All Mappings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:all-mappings}
     *
     * @return all of the stored mappings of an application
     */
    @Processor
    public String allMappings() {
        return getJanrainEngageClient().allMappings();
    }
    
    /**
     * Map
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:map}
     *
     * @param identifier The identifier returned from the auth_info API call.
     * @param primaryKey The primary key from your users table, as a string.
     * @param overwrite If false, only create the mapping if one does not already exist for the specified identifier.
     * @return true if the operation is successful
     */
    @Processor
    public boolean map(String identifier, String primaryKey, @Optional Boolean overwrite) {
        return getJanrainEngageClient().map(identifier, primaryKey, overwrite);
    }
    
    /**
     * Mappings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:mappings}
     *
     * @param primaryKey The primary key from your users table, as a string.
     * @return all the stored Identity Providers associated with a particular user’s primary key
     */
    @Processor
    public Identifiers mappings(String primaryKey) {
        return getJanrainEngageClient().mappings(primaryKey);
    }
    
    /**
     * Unmap
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:unmap}
     *
     * @param identifier The identifier currently mapped to the primaryKey.
     * @param allIdentifiers false is the default. If true, all identifiers mapped to the primaryKey are removed.
     * @param primaryKey The primary key from your users table, as a string.
     * @param unlink false is the default. If true, unlinks your application from the user’s account with the provider.
     * @return true if the operation is successful
     */
    @Processor
    public boolean unmap(String identifier, @Optional @Default("false") Boolean allIdentifiers, String primaryKey, Boolean unlink) {
        return getJanrainEngageClient().unmap(identifier, allIdentifiers, primaryKey, unlink);
    }
    
    /**
     * Broadcast
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:broadcast}
     *
     * @param identifier The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param deviceToken The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param title The title given to the shared content.
     * @param url The URL associated to the content being shared.
     * @param source URL of the site sharing the activity.
     * @param message Message associated with the activity being shared.
     * @param description The description of the shared content. This appears in the preview of the shared object and describes what is being shared.
     * @param image An image associated with the content being shared.
     * @param media The Flash or video object associated with the content being shared.
     * @param actionLink The link that appears below the user-generated message and content fields. In the case of Facebook, this link appears next to the Like and Comment links.
     * @param objectId Facebook only. Use this parameter to share to a Facebook fan page instead of the User’s wall. The value is the Object ID assigned to the fan page.
     * @return The response includes a share element which returns fields that were actually passed to the provider. 
     *         If the provider does not support a parameter, it will not be included in the result
     */
    @Processor
    public Broadcast broadcast(@Optional String identifier, @Optional String deviceToken, @Optional String title, 
            @Optional String url, @Optional String source, @Optional String message, @Optional String description, 
            @Optional String image, @Optional String media, @Optional String actionLink, @Optional String objectId) {
        return getJanrainEngageClient().broadcast(identifier, deviceToken, title, url, source, message, description, image, media, actionLink, objectId);
    }
    
    /**
     * Direct
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:direct}
     *
     * @param identifier The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param deviceToken The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param title The title given to the shared content.
     * @param url The URL associated to the content being shared.
     * @param recipients A list of identifiers in JSON associated with the recipients being contacted.
     * @param source URL of the site sharing the activity.
     * @param message Message associated with the activity being shared.
     * @param description The description of the shared content. This appears in the preview of the shared object and describes what is being shared.
     * @param image An image associated with the content being shared.
     * @param media The Flash or video object associated with the content being shared.
     * @param actionLink The link that appears below the user-generated message and content fields. In the case of Facebook, this link appears next to the Like and Comment links.
     * @param recipientUrls Allows for sharing multiple urls to multiple recipients. The value is a JSON object of recipients and shared urls.
     * @return The response includes a share element which returns fields that were actually passed to the provider. 
     *         If the provider does not support a parameter, it will not be included in the result
     */
    @Processor
    public Direct direct(@Optional String identifier, @Optional String deviceToken, @Optional String title, 
            @Optional String url, String recipients, @Optional String source, @Optional String message, @Optional String description, 
            @Optional String image, @Optional String media, @Optional String actionLink, @Optional String recipientUrls) {
        return getJanrainEngageClient().direct(identifier, deviceToken, title, url, recipients, source, message, description, image, media, actionLink, recipientUrls);
    }
    
    /**
     * Get Share Count
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-share-count}
     *
     * @param url The URL that was shared.
     * @param callback When a value is added, returns data in JSONP format.
     * @return he number of a times a given URL has been shared.
     */
    @Processor
    public String getShareCount(String url, @Optional String callback) {
        return getJanrainEngageClient().getShareCount(url, callback);
    }
    
    /**
     * Get Share Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-share-providers}
     *
     * @return a list of email and sharing providers configured for the widget.
     */
    @Processor
    public ShareProviders getShareProviders() {
        return getJanrainEngageClient().getShareProviders();
    }
    
    /**
     * Set Share Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-share-providers}
     *
     * @param share Sharing providers to add to the widget. This may be left empty, in which case the widget will have no sharing providers.
     * @param email Email providers to add to the widget. You can leave this empty, in which case the widget will have no email providers.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setShareProviders(String share, @Optional String email) {
        return getJanrainEngageClient().setShareProviders(share, email);
    }
    
    /**
     * Add Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-domain-patterns}
     *
     * @param domains A comma separated list of domains that will be used as a whitelist for the website.
     * @return true if the operation is successful
     */
    @Processor
    public boolean addDomainPatterns(String domains) {
        return getJanrainEngageClient().addDomainPatterns(domains);
    }
    
    /**
     * Get Backplane Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-backplane-properties}
     *
     * @return the backplane properties.
     */
    @Processor
    public Backplane getBackplaneProperties() {
        return getJanrainEngageClient().getBackplaneProperties();
    }
    
    /**
     * Get Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-domain-patterns}
     *
     * @return the domain patterns.
     */
    @Processor
    public DomainPatterns getDomainPatterns() {
        return getJanrainEngageClient().getDomainPatterns();
    }
    
    /**
     * Lookup Rp
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:lookup-rp}
     *
     * @param pluginName The name of your plugin.
     * @param pluginVersion The version number of your plugin.
     * @return the plugin response.
     */
    @Processor
    public Plugin lookupRp(@Optional String pluginName, @Optional String pluginVersion) {
        return getJanrainEngageClient().lookupRp(pluginName, pluginVersion);
    }
    
    /**
     * Set Backplane Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-backplane-properties}
     *
     * @param server The Backplane server’s domain name, such as, example.com.
     * @param bus The Backplane bus name.
     * @param version The Backplane server version, for example, v1.1. The default value is v1.
     * @param remove  false is the default. If false, add a new Backplane configuration; otherwise, 
     *                remove the Backplane configuration for the specified server or bus.
     * @param username Only required when you do not use remove. The user name for the Backplane credential.
     * @param password Only required when you do not use remove. The user name for the Backplane credential.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setBackplaneProperties(String server, String bus, @Optional @Default("v1") String version, @Optional Boolean remove, 
            String username, String password) {
        return getJanrainEngageClient().setBackplaneProperties(server, bus, version, remove, username, password);
    }
    
    /**
     * Set Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-domain-patterns}
     *
     * @param domains A comma separated list of domains used as a whitelist for the website.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setDomainPatterns(String domains) {
        return getJanrainEngageClient().setDomainPatterns(domains);
    }
    
    /**
     * Activity
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:activity}
     *
     * @param activity The activity structure, JSON-encoded.
     * @param identifier The identifier URL or device_token of the user sharing an activity. Do not use the device_token with mobile browsers.
     * @param deviceToken The identifier URL or device_token of the user sharing an activity. Do not use the device_token with mobile browsers.
     * @param truncate If true, truncate the activity update text when posting to providers which impose length restrictions (currently Twitter).
     * @param prependName If true, prepend the user’s name to the action when posting to Facebook (ignored for other providers).
     * @param urlShortening A boolean indicating whether to provide the entire URL in the post or tweet, or the shortened version. (PRO)
     * @param source Must be domain or URL. Defines a specific domain or URL as the source page of the sharing activity. Used by analytics to categorize posts by domain.
     * @return true if the operation is successful
     */
    @Processor
    public boolean activity(String activity, @Optional String identifier, @Optional String deviceToken, 
            @Optional @Default("true") Boolean truncate, @Optional @Default("true") Boolean prependName, @Optional String urlShortening, @Optional String source) {
        return getJanrainEngageClient().activity(activity, identifier, deviceToken, truncate, prependName, urlShortening, source);
    }
    
    /**
     * Auth Infos
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-infos}
     *
     * @param tokens The tokens parameter received at your token callback URL as described in Token Callback URL on the Token Callback URL page.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format.
     * @return data from more than one identity provider
     */
    @Processor
    public AuthInfos authInfos(String tokens, @Optional @Default("false") Boolean extended) {
        return getJanrainEngageClient().authInfos(tokens, extended);
    }
    
    /**
     * Set Status
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-status}
     *
     * @param identifier The identifier returned from the auth_info API call.
     * @param status The status message to set. Engage does not set a length restriction on this message, however Twitter and LinkedIn limit status length to 140 characters.
     * @param location This is a string containing location data associated with the content being published. 
     * @param truncate If true, truncate status when posting to providers that impose status length restrictions (currently Twitter, Yahoo, and LinkedIn).
     * @param source Must be domain or URL. Defines a specific domain or URL as the source page of the sharing activity. Used by analytics to categorize posts by domain.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setStatus(String identifier, String status, @Optional String location, @Optional @Default("true") Boolean truncate,
            @Optional String source) {
        return getJanrainEngageClient().setStatus(identifier, status, location, truncate, source);
    }
    
    /**
     * Add Bp Bus
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-bp-bus}
     *
     * @param partnerKey Enter your partnerKey.
     * @return The response includes the name of the new bus, and the name of the application with which it is associated.
     */
    @Processor
    public Map<String, String> addBpBus(String partnerKey) {
        return getJanrainPartnerClient().addBpBus(partnerKey);
    }
    
    /**
     * Apps
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:apps}
     *
     * @param partnerKey Enter your partnerKey.
     * @return List of applications managed by the partner. 
     */
    @Processor
    public Apps apps(String partnerKey) {
        return getJanrainPartnerClient().apps(partnerKey);
    }
    
    /**
     * Add Admin
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-admin}
     *
     * @param partnerKey You Engage partner key, which you can find on the dashboard.
     * @param email The email address of the admin user to be added.
     * @param verify Indicates whether a verification email is sent out, requiring the user to click on it before they get access to the website.
     * @return true if the operation is successful
     */
    @Processor
    public boolean addAdmin(String partnerKey, String email, @Optional @Default("true") Boolean verify) {
        return getJanrainPartnerClient().addAdmin(partnerKey, email, verify);
    }
    
    /**
     * Delete Admin
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:delete-admin}
     *
     * @param partnerKey You Engage partner key, which you can find on the dashboard.
     * @param email The email address of the admin user to be added.
     * @return true if the operation is successful
     */
    @Processor
    public boolean deleteAdmin(String partnerKey, String email) {
        return getJanrainPartnerClient().deleteAdmin(partnerKey, email);
    }
    
    /**
     * Get Admins
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-admins}
     *
     * @param partnerKey You Engage partner key, which you can find on the dashboard.
     * @return This call returns all admin users currently assigned to the RP.
     */
    @Processor
    public Admins getAdmins(String partnerKey) {
        return getJanrainPartnerClient().getAdmins(partnerKey);
    }
    
    /**
     * Add Domain
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-domain}
     *
     * @param partnerKey Engage partner key, which you can find on the dashboard.
     * @param engageApiKey Engage API Key, which you can find on the dashboard.
     * @param domain The domain to add.
     * @return true if the operation is successful.
     */
    @Processor
    public boolean addDomain(String partnerKey, String engageApiKey, String domain) {
        return getJanrainPartnerClient().addDomain(partnerKey, engageApiKey, domain);
    }
    
    /**
     * Create App
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:create-app}
     *
     * @param partnerKey Engage partner key, which you can find on the dashboard.
     * @param email The administrative email address to be associated with your new Engage application.
     * @param displayName The display name for your new Engage application.
     * @param domain The fully-qualified domain for your new Engage application.
     * @return This call creates a new Engage application. 
     */
    @Processor
    public AppInfo createApp(String partnerKey, String email, String displayName, String domain) {
        return getJanrainPartnerClient().createApp(partnerKey, email, displayName, domain);
    }
    
    /**
     * Create Invite
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:create-invite}
     *
     * @param engageApiKey Engage API Key, which you can find on the dashboard.
     * @param partnerKey Engage partner key, which you can find on the dashboard.
     * @param email The administrative email address to be associated with your new Engage application.
     * @return This call generates an email invitation for administrative access to an existing application.
     */
    @Processor
    public String createInvite(String engageApiKey, String partnerKey, String email) {
        return getJanrainPartnerClient().createInvite(engageApiKey, partnerKey, email);
    }
    
    /**
     * Delete App
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:delete-app}
     *
     * @param engageApiKey The Engage apiKey for the application to be deleted.
     * @param partnerKey The Engage partnerKey for the application that created the app referenced by apiKey.
     * @return true if the operation is successful.
     */
    @Processor
    public boolean deleteApp(String engageApiKey, String partnerKey) {
        return getJanrainPartnerClient().deleteApp(engageApiKey, partnerKey);
    }
    
    /**
     * Get Pending Invites
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-pending-invites}
     *
     * @param engageApiKey Engage API key for the application for which to return pending invites.
     * @param partnerKey The Engage partner key for the application that created the app referenced by the apiKey parameter.
     * @return the pending invites.
     */
    @Processor
    public Invites getPendingInvites(String engageApiKey, String partnerKey) {
        return getJanrainPartnerClient().getPendingInvites(engageApiKey, partnerKey);
    }
    
    /**
     * Get Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-properties}
     *
     * @param partnerKey The Engage partner key for the application that created the app referenced by the apiKey parameter.
     * @param engageApiKey Engage API key for the application for which to return pending invites.
     * @param provider The name of the provider whose properties you want to return. 
     * @return the app properties.
     */
    @Processor
    public Map<String, String> getProperties(String partnerKey, String engageApiKey, String provider) {
        return getJanrainPartnerClient().getProperties(engageApiKey, partnerKey, provider);
    }
    
    /**
     * Get Provider Permissions
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-provider-permissions}
     *
     * @param partnerKey The Engage partner key for the application that created the app referenced by the apiKey parameter.
     * @param engageApiKey Engage API key for the application for which to return pending invites.
     * @param provider The name of the provider whose properties you want to return. 
     * @return the provider permission.
     */
    @Processor
    public Permissions getProviderPermissions(String partnerKey, String engageApiKey, String provider) {
        return getJanrainPartnerClient().getProviderPermissions(engageApiKey, partnerKey, provider);
    }
    
    /**
     * Reset Api Key
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:reset-api-key}
     *
     * @param rpAppId The application identifier of the RP application for which you want to reset the API key.
     * @param partnerKey The Engage partner key for the application that created the app referenced by the apiKey parameter.
     * @return the new api key.
     */
    @Processor
    public String resetApiKey(String rpAppId, String partnerKey) {
        return getJanrainPartnerClient().resetApiKey(rpAppId, partnerKey);
    }
    
    /**
     * Set Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-properties}
     *
     * @param engageApiKey The Engage API Key of the application to configure.
     * @param partnerKey Your Engage partner key, which you can find on the dashboard.
     * @param provider The name of the provider to configure.
     * @param fbAppID Facebook only: The Application Id for the user’s Facebook application.
     * @param fbSecret Facebook Only: The Application Secret for the user’s Facebook application.
     * @param emailPerm Facebook only: Set to true if this application needs email to receive end-user email addresses.
     * @param uninstallURL Facebook only: This is the URL that is invoked when the user uninstalls the Facebook application.
     * @param consumerKey This is the Consumer Key for the user’s application. 
     * @param secret The consumer secret the user’s application.
     * @param paypalDisplayName PayPal only: The display name for the user’s Paypal application.
     * @param email PayPal only: enter a valid email address that is already registered with a PayPal account.
     * @param liveidAppID Windows Live only: The Application ID for the user’s Windows Live application.
     * @param liveidSecret Windows Live only: The Secret Key for the user’s Windows Live application.
     * @param liveidPrivacyPolicyUrl Windows Live only: The URL for the Windows Live application’s privacy policy.
     * @param yahooAppID Yahoo only: The Application ID for the user’s Yahoo application.
     * @param activityScopesSet Yahoo only: Set to true if the user’s Yahoo application has read and write permissions for “Status” and “Updates.”
     * @param contactsScopeSet Yahoo only: Set to true if the user’s Yahoo application has read permission for “Contacts.”
     * @return true if the operation is successful.
     */
    @Processor
    public boolean setProperties(String engageApiKey, String partnerKey, String provider, @Optional String fbAppID, @Optional String fbSecret,
            @Optional Boolean emailPerm, @Optional String uninstallURL, String consumerKey, String secret, @Optional String paypalDisplayName,
            @Optional String email, @Optional String liveidAppID, @Optional String liveidSecret, @Optional String liveidPrivacyPolicyUrl, 
            @Optional String yahooAppID, @Optional Boolean activityScopesSet, @Optional Boolean contactsScopeSet) {
        return getJanrainPartnerClient().setProperties(engageApiKey, partnerKey, provider, fbAppID, fbSecret, emailPerm, uninstallURL, 
                consumerKey, secret, paypalDisplayName, email, liveidAppID, liveidSecret, liveidPrivacyPolicyUrl, yahooAppID, 
                activityScopesSet, contactsScopeSet);
    }
    
    /**
     * Set Provider Permissions
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-provider-permissions}
     *
     * @param engageApiKey The Engage API Key of the application to configure.
     * @param partnerKey Your Engage partner key, which you can find on the dashboard.
     * @param provider The name of the provider to configure.
     * @param permissions A comma-separated list of permissions to set.
     * @return true if the operation is successful.
     */
    @Processor
    public boolean setProviderPermissions(String engageApiKey, String partnerKey, String provider, String permissions) {
        return getJanrainPartnerClient().setProviderPermissions(engageApiKey, partnerKey, provider, permissions);
    }
    
    /**
     * Verify Domain
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:verify-domain}
     *
     * @param engageApiKey The Engage API Key of the application to configure.
     * @param partnerKey Your Engage partner key, which you can find on the dashboard.
     * @param provider The name of the provider to configure.
     * @param code This is the Google-supplied META tag value that will be created on the domain.
     * @param filename This is the Yahoo-supplied filename that will be created on the domain. 
     * @return true if the operation is successful.
     */
    @Processor
    public boolean verifyDomain(String engageApiKey, String partnerKey, String provider, @Optional String code, @Optional String filename) {
        return getJanrainPartnerClient().verifyDomain(engageApiKey, partnerKey, provider, code, filename);
    }
    
    /**
     * Add Client
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-client}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param description A string description of the client.
     * @param features A JSON array of feature names that the client has; defaults to the empty list.
     * @return the created client
     */
    @Processor
    public ClientInfo addClient(String client_id, String client_secret, String description, @Optional String features) {
        return getJanrainCaptureClient().addClient(client_id, client_secret, description, features);
    }
    
    /**
     * Clear Whitelist
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:clear-whitelist}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client_id whose whitelist will be cleared.
     * @return true if the operation is successful
     */
    @Processor
    public boolean clearWhitelist(String client_id, String client_secret, @Optional String for_client_id) {
        return getJanrainCaptureClient().clearWhitelist(client_id, client_secret, for_client_id);
    }
    
    /**
     * Delete Client
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:delete-client}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param client_id_for_deletion The client_id to delete.
     * @return true if the operation is successful
     */
    @Processor
    public boolean deleteClient(String client_id, String client_secret, String client_id_for_deletion) {
        return getJanrainCaptureClient().deleteClient(client_id, client_secret, client_id_for_deletion);
    }
    
    /**
     * List Clients
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:list-clients}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param has_features A JSON array features names; only clients which have at least one of the features in the array will be displayed.
     * @return the clients
     */
    @Processor
    public ClientListInfo listClients(String client_id, String client_secret, @Optional String has_features) {
        return getJanrainCaptureClient().listClients(client_id, client_secret, has_features);
    }
    
    /**
     * Set Description
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-description}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client id of the client having it’s description changed.
     * @param description The new description for the target client.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setDescription(String client_id, String client_secret, @Optional String for_client_id, String description) {
        return getJanrainCaptureClient().setDescription(client_id, client_secret, for_client_id, description);
    }
    
    /**
     * Set Features
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-features}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client id of the client having it’s description changed.
     * @param features A JSON array of feature names to assign to the client. 
     * @return true if the operation is successful
     */
    @Processor
    public boolean setFeatures(String client_id, String client_secret, @Optional String for_client_id, String features) {
        return getJanrainCaptureClient().setFeatures(client_id, client_secret, for_client_id, features);
    }
    
    /**
     * Set Whitelist
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-whitelist}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client id of the client having it’s description changed.
     * @param whitelist A JSON array of CIDR addresses that make up the new whitelist for the client, each one in the x.x.x.x/x format.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setWhitelist(String client_id, String client_secret, @Optional String for_client_id, String whitelist) {
        return getJanrainCaptureClient().setWhitelist(client_id, client_secret, for_client_id, whitelist);
    }
    
    /**
     * Retrieve Entity
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:retrieve-entity}
     *
     * @param client_secret Required when authenticating with client settings. 
     * @param client_id Required when authenticating with client settings.
     * @param access_token Required when authenticating with an OAuth access_token. 
     * @param uuid Required when not using id or key_attribute paramaters. 
     * @param id Required when not using key_attribute or uuid parameters. 
     * @param key_attribute Required when not using id or uuid.
     * @param key_value Required when using key_attribute. 
     * @param password_attribute Entity can be used to validate user passwords. 
     * @param password_value A plaintext value that will be matched against the password attribute specified in the password_attribute parameter. 
     * @param type_name The entityType of the entity.
     * @param attribute_name This is a schema path to an individual attribute.
     * @param attributes This is a JSON array of attributes.
     * @param created Timestamps are generated when an entity is created.
     * @param last_updated Timestamps are generated when an entity is updated.
     * @return Retrieve an entity of entityType user by id.
     */
    @Processor
    public String retrieveEntity(@Optional String client_secret, @Optional String client_id, @Optional String access_token,
            @Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            @Optional String password_attribute, @Optional String password_value, String type_name, @Optional String attribute_name,
            @Optional String attributes, @Optional String created, @Optional String last_updated) {
        return getJanrainCaptureClient().retrieveEntity(client_secret, client_id, access_token, uuid, id, key_attribute, key_value, 
                password_attribute, password_value, type_name, attribute_name, attributes, created, last_updated);
    }
    
    /**
     * Entity Adopt
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-adopt}
     *
     * @param client_id The client identifier of the owner client.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param id The identifier of the entity.
     * @param access_token Required when authenticating with an OAuth access_token.
     * @param attribute_name The value path to the plural that is to adopt the orphan. 
     * @param child_id The id of the orphaned plural element to be adopted.
     * @return true if the operation is successful
     */
    @Processor
    public boolean entityAdopt(@Optional String client_secret, @Optional String client_id, String type_name, String id,
            @Optional String access_token, String attribute_name, String child_id) {
        return getJanrainCaptureClient().entityAdopt(client_secret, client_id, type_name, id, access_token, attribute_name, child_id);
    }
    
    /**
     * Entity Bulk Create
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-bulk-create}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param all_attributes The attribute names and values (as JSON) for the entity.
     * @return the bulk response
     */
    @Processor
    public BulkResponse entityBulkCreate(String client_id, String client_secret, String type_name, String all_attributes) {
        return getJanrainCaptureClient().entityBulkCreate(client_id, client_secret, type_name, all_attributes);
    }
    
    /**
     * Entity Count
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-count}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param filter The expression to use to filter the results.
     * @return the entity count
     */
    @Processor
    public String entityCount(String client_id, String client_secret, String type_name, @Optional String filter) {
        return getJanrainCaptureClient().entityCount(client_id, client_secret, type_name, filter);
    }
    
    /**
     * Entity Create
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-create}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param attributes The attribute names and values (as JSON) for the entity.
     * @param include_record When true, a result field is added to the response containing the data of the newly created entity record.
     * @return the entity created
     */
    @Processor
    public Map<String,String> entityCreate(String client_id, String client_secret, @Optional String type_name, String attributes, @Optional Boolean include_record) {
        return getJanrainCaptureClient().entityCreate(client_id, client_secret, type_name, attributes, include_record);
    }
    
    /**
     * Entity Delete
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-delete}
     *
     * @param client_secret Required when authenticating with client settings. 
     * @param client_id Required when authenticating with client settings.
     * @param access_token Required when authenticating with an OAuth access_token. 
     * @param uuid Required when not using id or key_attribute paramaters. 
     * @param id Required when not using key_attribute or uuid parameters. 
     * @param key_attribute Required when not using id or uuid.
     * @param key_value Required when using key_attribute. 
     * @param type_name The entityType of the entity.
     * @param attribute_name This is a schema path to an individual attribute.
     * @param created Timestamps are generated when an entity is created.
     * @param last_updated Timestamps are generated when an entity is updated.
     * @return true if the operation is successful
     */
    @Processor
    public boolean entityDelete(@Optional String client_secret, @Optional String client_id, @Optional String access_token,
            @Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String type_name, @Optional String attribute_name, @Optional String created, @Optional String last_updated) {
        return getJanrainCaptureClient().entityDelete(client_secret, client_id, access_token, uuid, id, key_attribute, key_value, 
                type_name, attribute_name, created, last_updated);
    }
    
    /**
     * Entity Bulk Delete
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-bulk-delete}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param filter The expression used to filter the results.
     * @param commit When the parameter is present, will not delete any records unless the value is true.
     * @return the count of the deleted entities
     */
    @Processor
    public String entityBulkDelete(String client_id, String client_secret, String type_name, String filter, @Optional Boolean commit) {
        return getJanrainCaptureClient().entityBulkDelete(client_id, client_secret, type_name, filter, commit);
    }
    
    /**
     * Entity Purge
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-purge}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The entityType of the entity.
     * @param commit When the parameter is present, will not delete any records unless the value is true.
     * @return the resulted state of the action
     */
    @Processor
    public String entityPurge(String client_id, String client_secret, String type_name, Boolean commit) {
        return getJanrainCaptureClient().entityPurge(client_id, client_secret, type_name, commit);
    }
    
    /**
     * Entity Replace
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-replace}
     *
     * @param client_secret Required when authenticating with client settings. 
     * @param client_id Required when authenticating with client settings.
     * @param access_token Required when authenticating with an OAuth access_token. 
     * @param uuid Required when not using id or key_attribute paramaters. 
     * @param id Required when not using key_attribute or uuid parameters. 
     * @param key_attribute Required when not using id or uuid.
     * @param key_value Required when using key_attribute. 
     * @param type_name The entityType of the entity.
     * @param value The JSON value to assign by attribute_name. 
     * @param attribute_name This is a schema path to an individual attribute.
     * @param created Timestamps are generated when an entity is created.
     * @param last_updated Timestamps are generated when an entity is updated.
     * @param include_record When true, a result field is added to the response, containing the data of the newly updated entity record.
     * @return true if the operation is successful
     */
    @Processor
    public boolean entityReplace(@Optional String client_secret, @Optional String client_id, @Optional String access_token,
            @Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String type_name, String value, @Optional String attribute_name, @Optional String created, @Optional String last_updated,
            @Optional Boolean include_record) {
        return getJanrainCaptureClient().entityReplace(client_secret, client_id, access_token, uuid, id, key_attribute, key_value, 
                type_name, value, attribute_name, created, last_updated, include_record);
    }
    
    /**
     * Entity Update
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-update}
     *
     * @param client_secret Required when authenticating with client settings. 
     * @param client_id Required when authenticating with client settings.
     * @param access_token Required when authenticating with an OAuth access_token. 
     * @param uuid Required when not using id or key_attribute paramaters. 
     * @param id Required when not using key_attribute or uuid parameters. 
     * @param key_attribute Required when not using id or uuid.
     * @param key_value Required when using key_attribute. 
     * @param type_name The entityType of the entity.
     * @param value The JSON value to assign by attribute_name. 
     * @param attribute_name This is a schema path to an individual attribute.
     * @param created Timestamps are generated when an entity is created.
     * @param last_updated Timestamps are generated when an entity is updated.
     * @param include_record When true, a result field is added to the response, containing the data of the newly updated entity record.
     * @return true if the operation is successful
     */
    @Processor
    public boolean entityUpdate(@Optional String client_secret, @Optional String client_id, @Optional String access_token,
            @Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String type_name, String value, @Optional String attribute_name, @Optional String created, @Optional String last_updated,
            @Optional Boolean include_record) {
        return getJanrainCaptureClient().entityUpdate(client_secret, client_id, access_token, uuid, id, key_attribute, key_value, 
                type_name, value, attribute_name, created, last_updated, include_record);
    }
    
    /**
     * Entity Find
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-find}
     *
     * @param client_secret Required when authenticating with client settings. 
     * @param client_id Required when authenticating with client settings.
     * @param type_name The entityType of the entity.
     * @param filter The expression used to filter the results. The default is to match all records.
     * @param max_results The maximum number of results to be returned. 
     * @param first_result Changes the first result displayed by the list to the next number specified.
     * @param show_total_count This includes a total_count in the result that shows the total number of records that matched the filter. 
     * @param sort_on A JSON array of attributes to sort by.
     * @param attributes A JSON array of attributes to return in the result set.
     * @return the results
     */
    @Processor
    public String entityFind(String client_secret, String client_id, String type_name, @Optional String filter,
            @Optional String max_results, @Optional String first_result, @Optional Boolean show_total_count, @Optional String sort_on, 
            @Optional String attributes) {
        return getJanrainCaptureClient().entityFind(client_secret, client_id, type_name, filter, max_results, 
                first_result, show_total_count, sort_on, attributes);
    }
    
    /**
     * Delete Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:delete-settings}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return true if the operation is successful
     */
    @Processor
    public boolean deleteSettings(String client_id, String client_secret, String key, String for_client_id) {
        return getJanrainCaptureClient().deleteSettings(client_id, client_secret, key, for_client_id);
    }
    
    /**
     * Delete Default
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:delete-default}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @return true if the operation is successful
     */
    @Processor
    public boolean deleteDefault(String client_id, String client_secret, String key) {
        return getJanrainCaptureClient().deleteDefault(client_id, client_secret, key);
    }
    
    /**
     * Get Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-settings}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the settings
     */
    @Processor
    public String getSettings(String client_id, String client_secret, String key, String for_client_id) {
        return getJanrainCaptureClient().getSettings(client_id, client_secret, key, for_client_id);
    }
    
    /**
     * Get MultiSettings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-multisettings}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the settings
     */
    @Processor
    public String getMultisettings(String client_id, String client_secret, String key, String for_client_id) {
        return getJanrainCaptureClient().getMultisettings(client_id, client_secret, key, for_client_id);
    }
    
    /**
     * Get Items
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-items}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the items
     */
    @Processor
    public String getItems(String client_id, String client_secret, String for_client_id) {
        return getJanrainCaptureClient().getItems(client_id, client_secret, for_client_id);
    }
    
    /**
     * Get Keys
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-keys}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the keys
     */
    @Processor
    public String getKeys(String client_id, String client_secret, String for_client_id) {
        return getJanrainCaptureClient().getKeys(client_id, client_secret, for_client_id);
    }
    
    /**
     * Set Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-settings}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @param value The value to assign to the key.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the settings
     */
    @Processor
    public String setSettings(String client_id, String client_secret, String key, String value, String for_client_id) {
        return getJanrainCaptureClient().setSettings(client_id, client_secret, key, value, for_client_id);
    }
    
    /**
     * Get Default
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-default}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @return the default setting
     */
    @Processor
    public String getDefault(String client_id, String client_secret, String key) {
        return getJanrainCaptureClient().getDefault(client_id, client_secret, key);
    }
    
    /**
     * Set Default
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-default}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param key The key to delete from the client settings.
     * @param value The value to assign to the key.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setDefault(String client_id, String client_secret, String key, String value) {
        return getJanrainCaptureClient().setDefault(client_id, client_secret, key, value);
    }
    
    /**
     * Set MultiSettings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-multisettings}
     *
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @param items A JSON object containing the key-value pairs to set for the client identifier.
     * @param for_client_id The client identifier whose key will be deleted.
     * @return the settings
     */
    @Processor
    public String setMultisettings(String client_id, String client_secret, String items, String for_client_id) {
        return getJanrainCaptureClient().setMultisettings(client_id, client_secret, items, for_client_id);
    }
    
    /**
     * Entity Versions
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:entity-versions}
     *
     * @param type_name The entityType of the entity.
     * @param id The primary key of the parent object.
     * @param timestamp The date and time to search for. Capture retrieves the value of the record as it existed at that timestamp.
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @return the versions
     */
    @Processor
    public String entityVersions(String type_name, String id, String timestamp, String client_id, String client_secret) {
        return getJanrainCaptureClient().entityVersions(type_name, id, timestamp, client_id, client_secret);
    }
    
    /**
     * Get Entity Type
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-entity-type}
     *
     * @param type_name The entityType of the entity.
     * @param timestamp The date and time to search for. Capture retrieves the value of the record as it existed at that timestamp.
     * @param client_id The client identifier.
     * @param client_secret The shared secret paired with the client_id.
     * @return the versions
     */
    @Processor
    public String getEntityType(String type_name, String timestamp, String client_id, String client_secret) {
        return getJanrainCaptureClient().getEntityType(type_name, timestamp, client_id, client_secret);
    }
    
    /**
     * Get Access Token
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-access-token}
     *
     * @param uuid Required when not using the id or key_attribute and key_value paramaters. 
     * @param id Required when not using the uuid or key_attribute and key_value paramaters. 
     * @param key_attribute Required when not using id or uuid parameters. 
     * @param key_value Required when using key_attribute. 
     * @param client_id The client identifier, which you can find on your dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The name of the entityType.
     * @param for_client_id The client_id for which to retrieve an accessToken.
     * @return Access Token
     */
    @Processor
    public String getAccessToken(@Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String client_id, String client_secret, String type_name, @Optional String for_client_id) {
        return getJanrainCaptureClient().getAccessToken(uuid, id, key_attribute, key_value, client_id, client_secret, type_name, for_client_id);
    }
    
    /**
     * Get Authorization Code
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-authorization-code}
     *
     * @param uuid Required when not using the id or key_attribute and key_value paramaters. 
     * @param id Required when not using the uuid or key_attribute and key_value paramaters. 
     * @param key_attribute Required when not using id or uuid parameters. 
     * @param key_value Required when using key_attribute. 
     * @param client_id The client identifier, which you can find on your dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param redirect_uri The redirect URI. This is the address used by CaptureUI to make the redirect.
     * @param type_name The name of the entityType.
     * @param transaction_state A JSON object that will be associated with the authorization code and returned when it is exchanged for an access_token and a refresh token.
     * @param lifetime The number of seconds for which the code is valid. The default value is 30 seconds.
     * @param for_client_id The client_id for which to retrieve an accessToken.
     * @return Authorization Code
     */
    @Processor
    public String getAuthorizationCode(@Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String client_id, String client_secret, String redirect_uri, String type_name, @Optional String transaction_state, @Optional String lifetime, 
            @Optional String for_client_id) {
        return getJanrainCaptureClient().getAuthorizationCode(uuid, id, key_attribute, key_value, client_id, client_secret, redirect_uri, type_name, 
                transaction_state, lifetime, for_client_id);
    }
    
    /**
     * Get Creation Token
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-creation-token}
     *
     * @param client_id The client identifier, which you can find on your dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The name of the entityType.
     * @param lifetime The number of seconds for which the code is valid. The default value is 30 seconds.
     * @param for_client_id The client_id for which to retrieve an accessToken.
     * @return Creation Token
     */
    @Processor
    public String getCreationToken(String client_id, String client_secret, String type_name, String lifetime, String for_client_id) {
        return getJanrainCaptureClient().getCreationToken(client_id, client_secret, type_name, lifetime, for_client_id);
    }
    
    /**
     * Get Verification Code
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-verification-code}
     *
     * @param uuid Required when not using id or the key_attribute and key_value parameters.
     * @param id The id number associated with the user record.
     * @param key_attribute Required when not using the id or uuid parameters.
     * @param key_value Required when using the key_attribute
     * @param client_id The client identifier, which you can find on your dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param type_name The name of the entityType.
     * @param attribute_name The name of the attribute to update when using the verification code.
     * @param lifetime The number of seconds for which the code is valid. The default value is 30 seconds.
     * @return Verification Code
     */
    @Processor
    public String getVerificationCode(@Optional String uuid, @Optional String id, @Optional String key_attribute, @Optional String key_value,
            String client_id, String client_secret, String type_name, String attribute_name, String lifetime) {
        return getJanrainCaptureClient().getVerificationCode(uuid, id, key_attribute, key_value, client_id, client_secret, type_name, attribute_name, lifetime);
    }
    
    /**
     * Use Verification Code
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:use-verification-code}
     *
     * @param verification_code The verification code obtained in a previous call to access/getVerificationCode.
     * @return true if the operation is successful
     */
    @Processor
    public boolean useVerificationCode(String verification_code) {
        return getJanrainCaptureClient().useVerificationCode(verification_code);
    }
    
    /**
     * Webhooks Add
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:webhooks-add}
     *
     * @param client_id The client identifier of the target Capture application, available in the dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param attributes This is only applicable when event_type is update. 
     * @param callback The URL address where the webhook message is to be delivered and processed. 
     * @param event_type The type of change that triggers the webhook. 
     * @param entity_type The schema where the attribute is defined. Most of the time, this will be the default schema user.
     * @return the created webhook
     */
    @Processor
    public String webhooksAdd(String client_id, String client_secret, @Optional String attributes, String callback, String event_type, String entity_type) {
        return getJanrainCaptureClient().webhooksAdd(client_id, client_secret, attributes, callback, event_type, entity_type);
    }
    
    /**
     * Webhooks Delete
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:webhooks-delete}
     *
     * @param client_id The client identifier of the target Capture application, available in the dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param uuid This is the uuid of the webhook.  
     * @return the deleted webhook
     */
    @Processor
    public String webhooksDelete(String client_id, String client_secret, String uuid) {
        return getJanrainCaptureClient().webhooksDelete(client_id, client_secret, uuid);
    }
    
    /**
     * Webhooks Find
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:webhooks-find}
     *
     * @param client_id The client identifier of the target Capture application, available in the dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param uuid This is the uuid of the webhook.  
     * @return the found webhook
     */
    @Processor
    public String webhooksFind(String client_id, String client_secret, String uuid) {
        return getJanrainCaptureClient().webhooksFind(client_id, client_secret, uuid);
    }
    
    /**
     * Webhooks List
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:webhooks-list}
     *
     * @param client_id The client identifier of the target Capture application, available in the dashboard.
     * @param client_secret The shared secret paired with the client_id.  
     * @return the list of webhooks
     */
    @Processor
    public String webhooksList(String client_id, String client_secret) {
        return getJanrainCaptureClient().webhooksList(client_id, client_secret);
    }
    
    /**
     * Webhooks Update
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:webhooks-update}
     *
     * @param client_id The client identifier of the target Capture application, available in the dashboard.
     * @param client_secret The shared secret paired with the client_id.
     * @param callback The URL address where the webhook message is to be delivered and processed.
     * @param event_type The type of change that triggers the webhook.
     * @param entity_type The schema where the attribute is defined. Most of the time, this will be the default schema user.
     * @param attributes This is applicable only when event_type is update.
     * @param uuid This is the uuid of the webhook.
     * @return the updated webhook
     */
    @Processor
    public String webhooksUpdate(String client_id, String client_secret, @Optional String callback, @Optional String event_type, 
            @Optional String entity_type, @Optional String attributes, String uuid) {
        return getJanrainCaptureClient().webhooksUpdate(client_id, client_secret, callback, event_type, entity_type, attributes, uuid);
    }
    
    /**
     * Auth Native
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-native}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param token A token for rpx.
     * @param thin_registration If true this endpoint will create nonexistent users. If it is false, you’ll need to do two-step registration using /oauth/register_native.
     * @param merge_token If you have had a previous call to /oauth/auth_native fail with code 380 email_address_in_use, you can merge the two accounts by passing a merge_token parameter while authorizing as the existing user.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A standard, mobile, native authorization. 
     */
    @Processor
    public String authNative(String client_id, String locale, String response_type, String redirect_uri, String token, 
            @Optional String thin_registration, @Optional String merge_token, @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().authNative(client_id, locale, response_type, redirect_uri, token, thin_registration, merge_token, flow_name, flow_version);
    }
    
    /**
     * Auth Native Traditional
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-native-traditional}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param email The parameter name is the traditional-registration email address field name in your flow, so this varies from application to application.
     * @param password The parameter name is the traditional-registration password field name in your flow, so this varies from application to application.
     * @param form The name of the login form in your flow.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A standard, mobile, native authorization.
     */
    @Processor
    public String authNativeTraditional(String client_id, String locale, String response_type, String redirect_uri, String email,
            String password, String form, @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().authNativeTraditional(client_id, locale, response_type, redirect_uri, email, password, form, flow_name, flow_version);
    }
    
    /**
     * Forgot Password Native
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:forgot-password-native}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param form The name of the form in your flow where you store the recover password logic..
     * @param email The email address for which you want to recover the password.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return the forgotten password 
     */
    @Processor
    public String forgotPasswordNative(String client_id, String locale, String response_type, String redirect_uri, String form, 
            String email, @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().forgotPasswordNative(client_id, locale, response_type, redirect_uri, form, email, flow_name, flow_version);
    }
    
    /**
     * Link Account Native
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:link-account-native}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param token The access token from a previous call to /oauth/auth_native or oauth/auth_native_traditional.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A linked account
     */
    @Processor
    public String linkAccountNative(String client_id, String locale, String response_type, String redirect_uri, String token, 
           @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().linkAccountNative(client_id, locale, response_type, redirect_uri, token, flow_name, flow_version);
    }
    
    /**
     * Register Native
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:register-native}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param token The access token from a previous call to /oauth/auth_native or oauth/auth_native_traditional.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A linked account
     */
    @Processor
    public String registerNative(String client_id, String locale, String response_type, String redirect_uri, String token, 
           @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().registerNative(client_id, locale, response_type, redirect_uri, token, flow_name, flow_version);
    }
    
    /**
     * Verify Email Native
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:verify-email-native}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param form The name of the form in your flow where you store the verify email logic.
     * @param email The email address you want to verify.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A linked account
     */
    @Processor
    public String verifyEmailNative(String client_id, String locale, String response_type, String redirect_uri, String form, String email, 
           @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().verifyEmailNative(client_id, locale, response_type, redirect_uri, form, email, flow_name, flow_version);
    }
    
    /**
     * Get Token
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-token}
     *
     * @param client_id The client identifier for your application
     * @param client_secret The shared secret paired with the client_id.
     * @param grant_type The access grant type included in the request. Available values are authorization_code and refresh_token. 
     * @param code The authorization code received from the authorization server. 
     * @param redirect_uri The redirection URI used in the initial request. CaptureUI uses this address to implement the redirect.
     * @param refresh_token The token for refreshing the
     * @return A token
     */
    @Processor
    public String getToken(String client_id, String client_secret, String grant_type, String code, String redirect_uri, @Optional String refresh_token) {
        return getJanrainCaptureClient().getToken(client_id, client_secret, grant_type, code, redirect_uri, refresh_token);
    }
    
    /**
     * Register Native Traditional
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:register-native-traditional}
     *
     * @param client_id The client identifier for your application.
     * @param locale The user’s flow locale for your application. 
     * @param response_type You must enter one of code, token, or code_and_token.
     * @param redirect_uri The value of the redirect_uri that was passed in to provision the authorization code, which Capture matches for security.
     * @param password The password of the person who is registering. Note: The actual name of this parameter is defined by your flow file. password is the default, but you might choose to change it.
     * @param password_confirm The confirmation for the user’s password and must match the password parameter.
     * @param email The email address you want to verify.
     * @param flow_name The name of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_name.
     * @param flow_version The version number of the flow you want to use for this user. If you do not enter a value, Capture uses default_flow_version.
     * @return A linked account
     */
    @Processor
    public String registerNativeTraditional(String client_id, String locale, String response_type, String redirect_uri, String password, String password_confirm,
            String email, @Optional String flow_name, @Optional String flow_version) {
        return getJanrainCaptureClient().registerNativeTraditional(client_id, locale, response_type, redirect_uri, password, password_confirm, email, flow_name, flow_version);
    }
    
    public JanrainEngageClient getJanrainEngageClient() {
        if (janrainEngageClient != null) {
            return janrainEngageClient;
        }
        janrainEngageClient = new JanrainEngageClientImpl(appName, appId, apiKey, jerseyClient, gson);
        return janrainEngageClient;
    }
    
    public JanrainPartnerClient getJanrainPartnerClient() {
        if (janrainPartnerClient != null) {
            return janrainPartnerClient;
        }
        janrainPartnerClient = new JanrainPartnerClientImpl(appName, appId, apiKey, jerseyClient, gson);
        return janrainPartnerClient;
    }
    
    public JanrainCaptureClient getJanrainCaptureClient() {
        if (janrainCaptureClient != null) {
            return janrainCaptureClient;
        }
        janrainCaptureClient = new JanrainCaptureClientImpl(captureHost, appId, apiKey, jerseyClient, gson);
        return janrainCaptureClient;
    }
    
    public Client getJerseyClient() {
        return jerseyClient;
    }

    public void setJerseyClient(Client jerseyClient) {
        this.jerseyClient = jerseyClient;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

	public String getCaptureHost() {
		return captureHost;
	}

	public void setCaptureHost(String captureHost) {
		this.captureHost = captureHost;
	}
    
    
    
}