/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain;

import java.util.Map;

import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Processor;

import org.mule.modules.janrain.responses.AuthInfos;
import org.mule.modules.janrain.responses.Backplane;
import org.mule.modules.janrain.responses.Broadcast;
import org.mule.modules.janrain.responses.Direct;
import org.mule.modules.janrain.responses.Identifiers;
import org.mule.modules.janrain.responses.Plugin;
import org.mule.modules.janrain.responses.ShareProviders;
import org.mule.modules.janrain.responses.UserInfo;
import org.mule.modules.janrain.responses.Contacts;
import org.mule.modules.janrain.responses.AvailableProviders;
import org.mule.modules.janrain.responses.WidgetProviders;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.api.json.JSONConfiguration;
import com.sun.jersey.core.impl.provider.entity.FormMultivaluedMapProvider;
import com.sun.jersey.core.impl.provider.entity.FormProvider;
import com.sun.jersey.core.impl.provider.entity.InputStreamProvider;
import com.sun.jersey.core.impl.provider.entity.MimeMultipartProvider;
import com.sun.jersey.multipart.impl.MultiPartWriter;

/**
 * Janrain Engage Cloud Connector for API V2.
 *
 * @author MuleSoft, Inc.
 */

@Connector(name="janrain", schemaVersion="2.0", friendlyName="Janrain", minMuleVersion="3.4")
public class JanrainConnector {
        
    /**
     * The App Name
     */
    private String appName;
    
    /**
     * The App ID
     */
    private String appId;
    
    /**
     * The Api Key
     */
    private String apiKey;
    
    /**
     * The Api's url
     */
    private final static String APIURL = ".rpxnow.com/api/v2/";
        
    /**
     * Janrain Client
     */
    private JanrainClient janrainClient;
    
    /**
     * The Api Resources
     */
    private WebResource apiResource;
    
    /**
     * Gson Parser
     */
    private Gson gson;
    
    /**
     * Connect
     *
     * @param apiKey the api Key
     * @param appName the app Name
     * @param appId the app Id
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String apiKey, String appName, String appId) throws ConnectionException {
        ClientConfig clientConfig = new DefaultClientConfig();
        clientConfig.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING, Boolean.TRUE);
        clientConfig.getClasses().add(MultiPartWriter.class);
        clientConfig.getClasses().add(MimeMultipartProvider.class);
        clientConfig.getClasses().add(InputStreamProvider.class);
        clientConfig.getClasses().add(FormProvider.class);
        clientConfig.getClasses().add(FormMultivaluedMapProvider.class);
        
        this.setAppId(appId);
        this.setApiKey(apiKey);
        this.setAppName(appName);
        this.gson = new GsonBuilder().create();
        this.setApiResource(Client.create(clientConfig).resource("https://" + appName + APIURL));
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        this.janrainClient = null;
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return (this.janrainClient != null);
    }

    /**
     * Connection Id
     */
    @ConnectionIdentifier
    public String connectionId() {
        return apiKey;
    }

    /**
     * Auth Info
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-info}
     *
     * @param token The token parameter received at your token_url.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format. 
     *        Ignored unless the application has a Pro or Enterprise service level.
     * @param tokenURL Validate the specified tokenURL value against the tokenURL that was originally sent. 
     * @return the auth info
     */
    @Processor
    public UserInfo authInfo(String token, @Optional Boolean extended, @Optional String tokenURL) {
        return getJanrainClient().authInfo(token, extended, tokenURL);
    }
    
    /**
     * Add Or Update Access Token
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-or-update-access-token}
     *
     * @param token The access_token to grant to the user. 
     *        These tokens need to be requested from the individual Identity Provider according to their particular API.
     * @param identifier The identifier associated with the provider. This needs to to be formatted as a URL with profile number.
     * @return true if the operation is successful
     */
    @Processor
    public boolean addOrUpdateAccessToken(String token, String identifier) {
        return getJanrainClient().addOrUpdateAccessToken(token, identifier);
    }
    
    /**
     * Analytics Access
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:analytics-access}
     *
     * @param start A date formatted as MM/DD/YYYY.
     * @param end A date formatted as MM/DD/YYYY.
     * @return the analytic data from your application
     */
    @Processor
    public Map<String, String> analyticsAccess(String start, String end) {
        return getJanrainClient().analyticsAccess(start, end);
    }
    
    /**
     * Get App Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-app-settings}
     *
     * @return the app settings
     */
    @Processor
    public Map<String, String> getAppSettings() {
        return getJanrainClient().getAppSettings();
    }
    
    /**
     * Get Available Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-available-providers}
     *
     * @return a list of configured providers for an application
     */
    @Processor
    public AvailableProviders getAvailableProviders() {
        return getJanrainClient().getAvailableProviders();
    }
    
    /**
     * Get Contacts
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-contacts}
     *
     * @param identifier The identifier returned from the auth_info API call. 
     *                   The application must be configured to request this information in the Provider Configuration screen.
     * @param contactType Specify friends to return identifiers for every friend of the user. 
     *                    If you do not specify a value, friends will be returned if available.
     * @param existingUser If true returns a value that identifies if a user has previously authenticated with the Janrain application before.
     * @return a list of all the contacts related to the user
     */
    @Processor
    public Contacts getContacts(String identifier, @Optional String contactType, @Optional Boolean existingUser) {
        return getJanrainClient().getContacts(identifier, contactType, existingUser);
    }
    
    /**
     * Get User Data
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-user-data}
     *
     * @param identifier The identifier returned from the auth_info API call. 
     *                   The application must be configured to request this information in the Provider Configuration screen.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format.
     * @return up-to-date copy of a user’s profile
     */
    @Processor
    public UserInfo getUserData(String identifier, @Optional Boolean extended) {
        return getJanrainClient().getUserData(identifier, extended);
    }
    
    /**
     * Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:providers}
     *
     * @return configured sign-in or social providers configured for a widget
     */
    @Processor
    public WidgetProviders providers() {
        return getJanrainClient().providers();
    }
    
    /**
     * Set App Settings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-app-settings}
     *
     * @param privacyPolicy Full URL to the location of your privacy policy.
     * @param favicon URL of your favicon.
     * @param domainRedirect The URL for the redirect.
     * @param postToTokenUrl A boolean, true or false.
     * @param oneTimeUseTokens A boolean, true or false.
     * @param googleProfileUrl A boolean, true or false.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setAppSettings(@Optional String privacyPolicy, @Optional String favicon, @Optional String domainRedirect, 
            @Optional Boolean postToTokenUrl, @Optional Boolean oneTimeUseTokens, @Optional Boolean googleProfileUrl) {
        return getJanrainClient().setAppSettings(privacyPolicy, favicon, domainRedirect, postToTokenUrl, oneTimeUseTokens, googleProfileUrl);
    }
    
    /**
     * Set Auth Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-auth-providers}
     *
     * @param providers A comma separated string of provider specifiers.
     * @param deviceType web, iphone, android.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setAuthProviders(String providers, @Optional String deviceType) {
        return getJanrainClient().setAuthProviders(providers, deviceType);
    }
    
    /**
     * All Mappings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:all-mappings}
     *
     * @return all of the stored mappings of an application
     */
    @Processor
    public String allMappings() {
        return getJanrainClient().allMappings();
    }
    
    /**
     * Map
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:map}
     *
     * @param identifier The identifier returned from the auth_info API call.
     * @param primaryKey The primary key from your users table, as a string.
     * @param overwrite If false, only create the mapping if one does not already exist for the specified identifier.
     * @return true if the operation is successful
     */
    @Processor
    public boolean map(String identifier, String primaryKey, @Optional Boolean overwrite) {
        return getJanrainClient().map(identifier, primaryKey, overwrite);
    }
    
    /**
     * Mappings
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:mappings}
     *
     * @param primaryKey The primary key from your users table, as a string.
     * @return all the stored Identity Providers associated with a particular user’s primary key
     */
    @Processor
    public Identifiers mappings(String primaryKey) {
        return getJanrainClient().mappings(primaryKey);
    }
    
    /**
     * Unmap
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:unmap}
     *
     * @param identifier The identifier currently mapped to the primaryKey.
     * @param allIdentifiers false is the default. If true, all identifiers mapped to the primaryKey are removed.
     * @param primaryKey The primary key from your users table, as a string.
     * @param unlink false is the default. If true, unlinks your application from the user’s account with the provider.
     * @return true if the operation is successful
     */
    @Processor
    public boolean unmap(String identifier, @Optional @Default("false") Boolean allIdentifiers, String primaryKey, Boolean unlink) {
        return getJanrainClient().unmap(identifier, allIdentifiers, primaryKey, unlink);
    }
    
    /**
     * Broadcast
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:broadcast}
     *
     * @param identifier The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param deviceToken The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param title The title given to the shared content.
     * @param url The URL associated to the content being shared.
     * @param source URL of the site sharing the activity.
     * @param message Message associated with the activity being shared.
     * @param description The description of the shared content. This appears in the preview of the shared object and describes what is being shared.
     * @param image An image associated with the content being shared.
     * @param media The Flash or video object associated with the content being shared.
     * @param actionLink The link that appears below the user-generated message and content fields. In the case of Facebook, this link appears next to the Like and Comment links.
     * @param objectId Facebook only. Use this parameter to share to a Facebook fan page instead of the User’s wall. The value is the Object ID assigned to the fan page.
     * @return The response includes a share element which returns fields that were actually passed to the provider. 
     *         If the provider does not support a parameter, it will not be included in the result
     */
    @Processor
    public Broadcast broadcast(@Optional String identifier, @Optional String deviceToken, @Optional String title, 
            @Optional String url, @Optional String source, @Optional String message, @Optional String description, 
            @Optional String image, @Optional String media, @Optional String actionLink, @Optional String objectId) {
        return getJanrainClient().broadcast(identifier, deviceToken, title, url, source, message, description, image, media, actionLink, objectId);
    }
    
    /**
     * Direct
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:direct}
     *
     * @param identifier The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param deviceToken The identifier URL or deviceToken of the user sharing an activity. Do not use the deviceToken with mobile browsers.
     * @param title The title given to the shared content.
     * @param url The URL associated to the content being shared.
     * @param recipients A list of identifiers in JSON associated with the recipients being contacted.
     * @param source URL of the site sharing the activity.
     * @param message Message associated with the activity being shared.
     * @param description The description of the shared content. This appears in the preview of the shared object and describes what is being shared.
     * @param image An image associated with the content being shared.
     * @param media The Flash or video object associated with the content being shared.
     * @param actionLink The link that appears below the user-generated message and content fields. In the case of Facebook, this link appears next to the Like and Comment links.
     * @param recipientUrls Allows for sharing multiple urls to multiple recipients. The value is a JSON object of recipients and shared urls.
     * @return The response includes a share element which returns fields that were actually passed to the provider. 
     *         If the provider does not support a parameter, it will not be included in the result
     */
    @Processor
    public Direct direct(@Optional String identifier, @Optional String deviceToken, @Optional String title, 
            @Optional String url, String recipients, @Optional String source, @Optional String message, @Optional String description, 
            @Optional String image, @Optional String media, @Optional String actionLink, @Optional String recipientUrls) {
        return getJanrainClient().direct(identifier, deviceToken, title, url, recipients, source, message, description, image, media, actionLink, recipientUrls);
    }
    
    /**
     * Get Share Count
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-share-count}
     *
     * @param url The URL that was shared.
     * @param callback When a value is added, returns data in JSONP format.
     * @return he number of a times a given URL has been shared.
     */
    @Processor
    public String getShareCount(String url, @Optional String callback) {
        return getJanrainClient().getShareCount(url, callback);
    }
    
    /**
     * Get Share Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-share-providers}
     *
     * @return a list of email and sharing providers configured for the widget.
     */
    @Processor
    public ShareProviders getShareProviders() {
        return getJanrainClient().getShareProviders();
    }
    
    /**
     * Set Share Providers
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-share-providers}
     *
     * @param share Sharing providers to add to the widget. This may be left empty, in which case the widget will have no sharing providers.
     * @param email Email providers to add to the widget. You can leave this empty, in which case the widget will have no email providers.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setShareProviders(String share, @Optional String email) {
        return getJanrainClient().setShareProviders(share, email);
    }
    
    /**
     * Add Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:add-domain-patterns}
     *
     * @param domains A comma separated list of domains that will be used as a whitelist for the website.
     * @return true if the operation is successful
     */
    @Processor
    public boolean addDomainPatterns(String domains) {
        return getJanrainClient().addDomainPatterns(domains);
    }
    
    /**
     * Get Backplane Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-backplane-properties}
     *
     * @return the backplane properties.
     */
    @Processor
    public Backplane getBackplaneProperties() {
        return getJanrainClient().getBackplaneProperties();
    }
    
    /**
     * Get Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:get-domain-patterns}
     *
     * @return the domain patterns.
     */
    @Processor
    public String getDomainPatterns() {
        return getJanrainClient().getDomainPatterns();
    }
    
    /**
     * Lookup Rp
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:lookup-rp}
     *
     * @param pluginName The name of your plugin.
     * @param pluginVersion The version number of your plugin.
     * @return the plugin response.
     */
    @Processor
    public Plugin lookupRp(@Optional String pluginName, @Optional String pluginVersion) {
        return getJanrainClient().lookupRp(pluginName, pluginVersion);
    }
    
    /**
     * Set Backplane Properties
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-backplane-properties}
     *
     * @param server The Backplane server’s domain name, such as, example.com.
     * @param bus The Backplane bus name.
     * @param version The Backplane server version, for example, v1.1. The default value is v1.
     * @param remove  false is the default. If false, add a new Backplane configuration; otherwise, 
     *                remove the Backplane configuration for the specified server or bus.
     * @param username Only required when you do not use remove. The user name for the Backplane credential.
     * @param password Only required when you do not use remove. The user name for the Backplane credential.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setBackplaneProperties(String server, String bus, @Optional @Default("v1") String version, @Optional Boolean remove, 
            String username, String password) {
        return getJanrainClient().setBackplaneProperties(server, bus, version, remove, username, password);
    }
    
    /**
     * Set Domain Patterns
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-domain-patterns}
     *
     * @param domains A comma separated list of domains used as a whitelist for the website.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setDomainPatterns(String domains) {
        return getJanrainClient().setDomainPatterns(domains);
    }
    
    /**
     * Activity
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:activity}
     *
     * @param activity The activity structure, JSON-encoded.
     * @param identifier The identifier URL or device_token of the user sharing an activity. Do not use the device_token with mobile browsers.
     * @param deviceToken The identifier URL or device_token of the user sharing an activity. Do not use the device_token with mobile browsers.
     * @param truncate If true, truncate the activity update text when posting to providers which impose length restrictions (currently Twitter).
     * @param prependName If true, prepend the user’s name to the action when posting to Facebook (ignored for other providers).
     * @param urlShortening A boolean indicating whether to provide the entire URL in the post or tweet, or the shortened version. (PRO)
     * @param source Must be domain or URL. Defines a specific domain or URL as the source page of the sharing activity. Used by analytics to categorize posts by domain.
     * @return true if the operation is successful
     */
    @Processor
    public boolean activity(String activity, @Optional String identifier, @Optional String deviceToken, 
            @Optional @Default("true") Boolean truncate, @Optional @Default("true") Boolean prependName, @Optional String urlShortening, @Optional String source) {
        return getJanrainClient().activity(activity, identifier, deviceToken, truncate, prependName, urlShortening, source);
    }
    
    /**
     * Auth Infos
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:auth-infos}
     *
     * @param tokens The tokens parameter received at your token callback URL as described in Token Callback URL on the Token Callback URL page.
     * @param extended Returns the extended Simple Registration and HCard data in addition to the normalized Portable Contacts format.
     * @return data from more than one identity provider
     */
    @Processor
    public AuthInfos authInfos(String tokens, @Optional @Default("false") Boolean extended) {
        return getJanrainClient().authInfos(tokens, extended);
    }
    
    /**
     * Set Status
     *
     * {@sample.xml ../../../doc/janrain-connector.xml.sample janrain:set-status}
     *
     * @param identifier The identifier returned from the auth_info API call.
     * @param status The status message to set. Engage does not set a length restriction on this message, however Twitter and LinkedIn limit status length to 140 characters.
     * @param location This is a string containing location data associated with the content being published. 
     * @param truncate If true, truncate status when posting to providers that impose status length restrictions (currently Twitter, Yahoo, and LinkedIn).
     * @param source Must be domain or URL. Defines a specific domain or URL as the source page of the sharing activity. Used by analytics to categorize posts by domain.
     * @return true if the operation is successful
     */
    @Processor
    public boolean setStatus(String identifier, String status, @Optional String location, @Optional @Default("true") Boolean truncate,
            @Optional String source) {
        return getJanrainClient().setStatus(identifier, status, location, truncate, source);
    }
    
    public JanrainClient getJanrainClient() {
        if (janrainClient != null) {
            return janrainClient;
        }
        janrainClient = new JanrainClientImpl(appName, appId, apiKey, apiResource, gson);
        return janrainClient;
    }
    
    public WebResource getApiResource() {
        return apiResource;
    }

    public void setApiResource(WebResource apiResource) {
        this.apiResource = apiResource;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }
        
}