/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.exception;

public class JanrainException extends RuntimeException {

    private static final long serialVersionUID = -2262847299350634241L;

    public JanrainException() {
        super();
    }
    
    public JanrainException(String message) {
        super(message);
    }
        
    public JanrainException(String message, Throwable cause) {
        super(message, cause);
    }
    
}