/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.exception;

public class JanrainException extends RuntimeException {

    private static final long serialVersionUID = -2262847299350634241L;

    public JanrainException(String message) {
        super(message);
    }
        
    public JanrainException(String message, Throwable cause) {
        super(message, cause);
    }
    
}