/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.client;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;

import org.mule.modules.janrain.exception.JanrainException;

import com.google.gson.Gson;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.client.ClientResponse.Status;

public class JanrainClientImpl {
    
    private Gson gson;
    private String appId;
    private String apiKey;
    private String appName;
    private WebResource apiResource;
    
    public JanrainClientImpl(String appName, String appId, String apiKey, Gson gson) {
        this.appName = appName;
        this.apiKey = apiKey;
        this.appId = appId;
        this.gson = gson;
    }
    
    protected ClientResponse execute(String path, MultivaluedMap<String, String> params, MediaType type, String method) {
        ClientResponse response;
        
        if (params != null) 
            response = getApiResource().path(path).queryParams(params).accept(type).method(method, ClientResponse.class);
        else
            response = getApiResource().path(path).accept(type).method(method, ClientResponse.class);
        
        if (response.getClientResponseStatus() != Status.OK) 
            throw new JanrainException(response.getEntity(String.class));
        else 
            return response;
    }
    
    public Gson getGson() {
        return gson;
    }

    public void setGson(Gson gson) {
        this.gson = gson;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public WebResource getApiResource() {
        return apiResource;
    }

    public void setApiResource(WebResource apiResource) {
        this.apiResource = apiResource;
    }

}