/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain.capture;

import java.util.List;

import org.mule.modules.janrain.engage.ApiResponse;

public class BulkResponse extends ApiResponse {

    private List<String> uuid_results;
    private List<Integer> results;
    
    public List<String> getUuid_results() {
        return uuid_results;
    }
    
    public void setUuid_results(List<String> uuid_results) {
        this.uuid_results = uuid_results;
    }
    
    public List<Integer> getResults() {
        return results;
    }
    
    public void setResults(List<Integer> results) {
        this.results = results;
    }
    
}