/**
 * (c) 2003-2015 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.janrain;

import org.junit.Assert;
import org.junit.Test;


public class JanrainConnectorTest {
	
	@Test
	public void dummyTest() {
		Assert.assertTrue(true);
	}
}