/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
//
//package org.mule.modules.janrain;
//
//import java.util.Map;
//import org.junit.Before;
//import org.junit.Test;
//import org.mule.api.ConnectionException;
//import org.mule.modules.janrain.capture.BulkResponse;
//import org.mule.modules.janrain.capture.ClientInfo;
//import org.mule.modules.janrain.engage.AuthInfos;
//import org.mule.modules.janrain.engage.AvailableProviders;
//import org.mule.modules.janrain.engage.Backplane;
//import org.mule.modules.janrain.engage.Broadcast;
//import org.mule.modules.janrain.engage.Contacts;
//import org.mule.modules.janrain.engage.Direct;
//import org.mule.modules.janrain.engage.Identifiers;
//import org.mule.modules.janrain.engage.Plugin;
//import org.mule.modules.janrain.engage.ShareProviders;
//import org.mule.modules.janrain.engage.UserInfo;
//import org.mule.modules.janrain.engage.WidgetProviders;
//import org.mule.modules.janrain.partner.Admins;
//import org.mule.modules.janrain.partner.AppInfo;
//import org.mule.modules.janrain.partner.Apps;
//import org.mule.modules.janrain.partner.Invites;
//import org.mule.modules.janrain.partner.Permissions;
//
//public class JanrainConnectorTest {
//    
//    private static final String API_KEY = "API_KEY";
//    private static final String APP_NAME = "APP_NAME";
//    private static final String APP_ID = "APP_ID";
//    private JanrainConnector connector;
//    
//    @Before
//    public void init() throws ConnectionException {
//        connector = new JanrainConnector();
//        connector.connect(API_KEY, APP_NAME, APP_ID);
//    }
//    
//    @Test
//    public void testAuthInfo() {
//        UserInfo response =  connector.authInfo("myToken", true, "myTokenUrl");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddOrUpdateAccessToken() {
//        boolean response =  connector.addOrUpdateAccessToken("myToken", "myIdentifier");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAnalyticsAccess() {
//        Map<String, String> response =  connector.analyticsAccess("10/04/2013", "30/04/2013");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetAppSettings() {
//        Map<String, String> response =  connector.getAppSettings();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetAvailableProviders() {
//        AvailableProviders response =  connector.getAvailableProviders();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetContacts() {
//        Contacts response =  connector.getContacts("identifier", "contactType", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetUserData() {
//        UserInfo response =  connector.getUserData("identifier", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testProviders() {
//        WidgetProviders response =  connector.providers();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetAppSettings() {
//        boolean response =  connector.setAppSettings(null, null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetAuthProviders() {
//        boolean response =  connector.setAuthProviders("google", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAllMappings() {
//        String response =  connector.allMappings();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testMap() {
//        boolean response =  connector.map("identifier", "primaryKey", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testMappings() {
//        Identifiers response =  connector.mappings("primaryKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testUnmap() {
//        boolean response =  connector.unmap("identifier", true, "primaryKey", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testBroadcast() {
//        Broadcast response =  connector.broadcast("identifier", null, null, null, null, null, null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDirect() {
//        Direct response =  connector.direct("identifier", null, null, null, "recipients", null, null, null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetShareCount() {
//        String response =  connector.getShareCount("www.google.com", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetShareProviders() {
//        ShareProviders response =  connector.getShareProviders();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetShareProviders() {
//        boolean response =  connector.setShareProviders("google", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddDomainPatterns() {
//        boolean response =  connector.addDomainPatterns("www.google.com");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetBackplaneProperties() {
//        Backplane response =  connector.getBackplaneProperties();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetDomainPatterns() {
//        String response =  connector.getDomainPatterns();
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testLookupRp() {
//        Plugin response =  connector.lookupRp(null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetBackplaneProperties() {
//        boolean response =  connector.setBackplaneProperties("server", "bus", "v1", true, "username", "password");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetDomainPatterns() {
//        boolean response =  connector.setDomainPatterns("google.com");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testActivity() {
//        boolean response =  connector.activity("{\"action\": \"wrote a review of Atomic Pizza\", \"url\": \"http://example.com/reviews/12345/\"}", "myIdentifier", null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAuthInfos() {
//        AuthInfos response =  connector.authInfos("token1, token2", true);
//        System.out.println(response);
//    }
//
//    @Test
//    public void testSetStatus() {
//        boolean response =  connector.setStatus("myIdentifier", "myStatus", null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddBpBus() {
//        Map<String, String> response =  connector.addBpBus("myPartnerKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testApps() {
//        Apps response =  connector.apps("myPartnerKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddAdmin() {
//        boolean response =  connector.addAdmin("myPartnerKey", "myEmail", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDeleteAdmin() {
//        boolean response =  connector.deleteAdmin("myPartnerKey", "myEmail");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetAdmins() {
//        Admins response =  connector.getAdmins("myPartnerKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddDomain() {
//        boolean response =  connector.addDomain("myPartnerKey", "myEngageApiKey", "myDomain");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testCreateApp() {
//        AppInfo response =  connector.createApp("partnerKey", "email", "displayName", "domain");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testCreateInvite() {
//        String response =  connector.createInvite("myEngageApiKey", "partnerKey", "email");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDeleteApp() {
//        boolean response =  connector.deleteApp("myPartnerKey", "myEngageApiKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetPendingInvites() {
//        Invites response =  connector.getPendingInvites("myPartnerKey", "myEngageApiKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetProperties() {
//        Map<String, String> response =  connector.getProperties("myPartnerKey", "myEngageApiKey", "myProvider");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetProviderPermissions() {
//        Permissions response =  connector.getProviderPermissions("myPartnerKey", "myEngageApiKey", "myProvider");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testResetApiKey() {
//        String response =  connector.resetApiKey("myRpAppId", "myPartnerKey");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testsetProperties() {
//        boolean response =  connector.setProperties("myEngageApiKey", "myPartnerKey", "myProvider", null, null, null, null, "myConsumerKey", "mySecret", null, null, null, null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetProviderPermissions() {
//        boolean response =  connector.setProviderPermissions("myEngageApiKey", "myPartnerKey", "myProvider", "myPermissions");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testVerifyDomain() {
//        boolean response =  connector.verifyDomain("myEngageApiKey", "myPartnerKey", "myProvider", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAddClient() {
//        ClientInfo response =  connector.addClient("client_id", "client_secret", "description", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testClearWhitelist() {
//        boolean response =  connector.clearWhitelist("client_id", "client_secret", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDeleteClient() {
//        boolean response =  connector.deleteClient("client_id", "client_secret", "client_id_for_deletion");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testListClients() {
//        ClientInfo response =  connector.listClients("client_id", "client_secret", "has_features");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetDescription() {
//        boolean response =  connector.setDescription("client_id", "client_secret", "for_client_id", "description");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetFeatures() {
//        boolean response =  connector.setFeatures("client_id", "client_secret", "for_client_id", "features");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetWhilelist() {
//        boolean response =  connector.setWhitelist("client_id", "client_secret", "for_client_id", "whitelist");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testRetrieveEntity() {
//        String response =  connector.retrieveEntity(null, null, "access_token", "uuid", null, null, null, null, null, "type_name", null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityAdopt() {
//        boolean response =  connector.entityAdopt(null, null, "type_name", "id", "access_token", "attribute_name", "child_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityBulkCreate() {
//        BulkResponse response =  connector.entityBulkCreate("client_id", "client_secret", "type_name", "all_attributes");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityCount() {
//        String response =  connector.entityCount("client_id", "client_secret", "type_name", "filter");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityCreate() {
//        Map<String, String> response =  connector.entityCreate("client_id", "client_secret", "type_name", "attributes", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityDelete() {
//        boolean response =  connector.entityDelete(null, null, "access_token", "uuid", null, null, null, "type_name", null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityBulkDelete() {
//        String response =  connector.entityBulkDelete("client_id", "client_secret", "type_name", "filter", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityPurge() {
//        String response =  connector.entityPurge("client_id", "client_secret", "type_name", true);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityReplace() {
//        boolean response =  connector.entityReplace(null, null, "access_token", "uuid", null, null, null, "type_name", "value", null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityUpdate() {
//        boolean response =  connector.entityUpdate(null, null, "access_token", "uuid", null, null, null, "type_name", "value", null, null, null, null, "attributes");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityFind() {
//        String response =  connector.entityFind("client_secret", "client_id", "type_name", null, null, null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDeleteSettings() {
//        boolean response =  connector.deleteSettings("client_id", "client_secret", "key", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testDeleteDefault() {
//        boolean response =  connector.deleteDefault("client_id", "client_secret", "key");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetSettings() {
//        String response =  connector.getSettings("client_id", "client_secret", "key", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetMultisettings() {
//        String response =  connector.getMultisettings("client_id", "client_secret", "key", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetItems() {
//        String response =  connector.getItems("client_id", "client_secret", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetKeys() {
//        String response =  connector.getKeys("client_id", "client_secret", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetDefault() {
//        String response =  connector.getDefault("client_id", "client_secret", "key");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetDefault() {
//        boolean response =  connector.setDefault("client_id", "client_secret", "key", "value");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testSetMultisettings() {
//        String response =  connector.setMultisettings("client_id", "client_secret", "items", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testEntityVersions() {
//        String response =  connector.entityVersions("type_name", "id", "timestamp", "client_id", "client_secret");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetEntityType() {
//        String response =  connector.getEntityType("type_name", "timestamp", "client_id", "client_secret");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetAccessToken() {
//        String response =  connector.getAccessToken(null, "id", null, null, "client_id", "client_secret", "type_name", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetAuthorizationCode() {
//        String response =  connector.getAuthorizationCode(null, "id", null, null, "client_id", "client_secret", "redirect_uri", "type_name", null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetCreationToken() {
//        String response =  connector.getCreationToken("client_id", "client_secret", "type_name", "lifetime", "for_client_id");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetVerificationCode() {
//        String response =  connector.getVerificationCode(null, "id", null, null, "client_id", "client_secret", "type_name", "attribute_name", "lifetime");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testUseVerificationCode() {
//        boolean response =  connector.useVerificationCode("verificationCode");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testWebhooksAdd() {
//        String response =  connector.webhooksAdd("client_id", "client_secret", null, "callback", "event_type", "entity_type");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testWebhooksDelete() {
//        String response =  connector.webhooksDelete("client_id", "client_secret", "uuid");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testWebhooksFind() {
//        String response =  connector.webhooksFind("client_id", "client_secret", "uuid");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testWebhooksList() {
//        String response =  connector.webhooksList("client_id", "client_secret");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testWebhooksUpdate() {
//        String response =  connector.webhooksUpdate("client_id", "client_secret", null, null, null, null, "uuid");
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAuthNative() {
//        String response =  connector.authNative("client_id", "locale", "response_type", "redirect_uri", "token", null, null, null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testAuthNativeTraditional() {
//        String response =  connector.authNativeTraditional("client_id", "locale", "response_type", "redirect_uri", "email", "password", "form", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testForgotPasswordNative() {
//        String response =  connector.forgotPasswordNative("client_id", "locale", "response_type", "redirect_uri", "form", "email", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testLinkAccountNative() {
//        String response =  connector.linkAccountNative("client_id", "locale", "response_type", "redirect_uri", "token", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testRegisterNative() {
//        String response =  connector.registerNative("client_id", "locale", "response_type", "redirect_uri", "token", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testVerifyEmailNative() {
//        String response =  connector.verifyEmailNative("client_id", "locale", "response_type", "redirect_uri", "form", "email", null, null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testGetToken() {
//        String response =  connector.getToken("client_id", "client_secret", "grant_type", "code", "redirect_uri", null);
//        System.out.println(response);
//    }
//    
//    @Test
//    public void testRegisterNativeTraditional() {
//        String response =  connector.registerNativeTraditional("client_id", "locale", "response_type", "redirect_uri", "password", "password_confirm", "email", null, null);
//        System.out.println(response);
//    }
//    
//}